# -*- coding: utf-8 -*-
"""DuttaSagnikAsn2b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-e2mlbrKLYKCejStROY5OC1i4UFXUg2
"""

#Sagnik dutta - Assignment 2B
height = float(input("Enter height in inches: "))
weight = float(input("Enter weight in pound: "))
healthy_bmi= 24.9
bmi = weight/(height*height)*703 
print (" your BMI is : %0.2f " %bmi)
if ( bmi >= 18.5 and bmi < 25):
   print ("your healthy")
elif ( bmi >= 25 ):
      bmi_diff = float(healthy_bmi - bmi)
      healthy_weight = float(healthy_bmi / 703)* (height*height)
      weight_diff = float(weight - healthy_weight)
      print (" weight to loose for healthy bmi is  %0.2f " %weight_diff)
elif ( bmi <= 18.5 ):
      bmi_diff = float(healthy_bmi - bmi)
      healthy_weight = float(healthy_bmi / 703)* (height*height)
      weight_diff = float(healthy_weight- weight)
      print (" weight to gain for healthy bmi is  %0.2f " %weight_diff)

